name: BSDs

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  BSDs:
    # Run BSDs using virtualization
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            version: '14.0'
            pkginstall: pkg install -y p5-ExtUtils-MakeMaker

          - name: openbsd
            version: '7.5'
            pkginstall: echo no packages required

          - name: netbsd
            version: '10.0'
            pkginstall: pkgin -y install perl || true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@ca9fe7f47c8b3d2caa669a290572e1eebf1c75f1
        with:
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            sudo ${{ matrix.os.pkginstall }}
            /usr/sbin/pkg_info || true
            curl -L https://cpanmin.us | sudo perl - --notest --installdeps --with-configure --with-develop .
            seq --version ||true
            cc -Wall -xc pending_signal_c ||true
            for n in `seq 15`; do ./a.out || echo $?; done
            echo BARRIER1
            cc -DREBLOCK -Wall -xc pending_signal_c ||true
            for n in `seq 15`; do ./a.out || echo $?; done
            echo BARRIER2
            perl Makefile.PL
            make
            ktrace -di env IPCRUNDEBUG=gory perl -Iblib/lib t/kill_kill.t || true
            kdump -dE -m128 || true
            IPCRUNDEBUG=gory prove -wlvmb t/kill_kill.t
