name: windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  perl:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0
      GITHUB_WINDOWS_TESTING: 1

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@master
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo C:\strawberry\perl\bin >>$GITHUB_PATH
          echo C:\strawberry\perl\site\bin >>$GITHUB_PATH
          echo C:\strawberry\c\bin >>$GITHUB_PATH
          echo C:\nosuch1 >>$GITHUB_PATH
          echo C:\nosuch2 >>$GITHUB_PATH
          echo $GITHUB_PATH
          echo $Env:Path
      - name: Confirm PATH
        run: echo $Env:Path
      - name: perl -V
        run: perl -V
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: make test
        run: make test
