name: Windows_Installation

on:
  schedule:
    - cron: '32 4 * * 1'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
          distribution: strawberry
      - run: perl -V
      - name: Uninstall and Install Module
        run: curl https://cpanmin.us | perl - --verbose --reinstall IPC::Run
