name: windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  perl:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0
      GITHUB_WINDOWS_TESTING: 1

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@master
      - name: Set up Perl
        run: |
          "This is now installed by default and is already in the path.  No
          other Perl is in the path.  Hence, these commands provide
          future-proofing only."
          choco install strawberryperl
          "C:\strawberry\perl\bin" >>$Env:GITHUB_PATH
          "C:\strawberry\perl\site\bin" >>$Env:GITHUB_PATH
          "C:\strawberry\c\bin" >>$Env:GITHUB_PATH
      - name: perl -V
        run: perl -V
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: make test
        run: make test
