name: windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0
      GITHUB_WINDOWS_TESTING: 1
      PERL_SIGNALS: unsafe

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@master
      - name: perl -V
        run: perl -V
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: make test
        run: make test TEST_FILES='-Ixlib -MTime::Limit=-group,-verbose,1 t/*.t'
